# Lattice Planner Parameters
lh_grid_lb: 0.0
lh_grid_ub: 1.0
traj_points: 15
traj_v_scale: 1.0
traj_v_span_min: 0.1
traj_v_span_max: 1.0
traj_v_span_num: 19

# Cost Functions
get_follow_optim_cost: true
get_map_collision: true
get_similarity_cost: true
weights_num: 4
ittc_thres: 2.0
scan_num: 144

# Parameter Configuration
params_num: !!python/tuple
- 1
- 4
params_name: !!python/tuple
- traj_v_scale
- cost_weights
params_dict:
  '0': speed
  '1': follow_optim
  '2': abs_speed_reward
  '3': curvature_speed_punish
  '4': opponent_collision

# Tracker Configuration (Pure Pursuit)
tracker_steps: 10
vel_scale: 1.0

# Pure Pursuit Specific Parameters
minL: 0.5
maxL: 1.8
Lscale: 8.0
minP: 0.5
maxP: 0.8
Pscale: 8.0
D: 0.2
interpScale: 10

# Waypoint Indices for Pure Pursuit
wpt_xind: 1
wpt_yind: 2
wpt_vind: 5

# Data Collection States
rollout_states: !!python/tuple
- rollout_obs
- rollout_ego_s
- rollout_opp_s
- ego_best_traj_idx
- opp_best_traj_idx
- ego_prev_traj
- ego_prev_opp
- ego_ittc
- ego_control_error
- abs_ittc